services:
  auditoria_bot:
    env_file: "config.env"
    image: pdkonovalov/auditoria_bot
    depends_on:
      - auditoria_bot_postgres
    restart: unless-stopped
  auditoria_bot_postgres:
    env_file: "config.env"
    image: postgres
    volumes:
      - auditoria_bot_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
volumes:
  auditoria_bot_postgres_data:
